"""Utilities for Magic AI experiments."""

from magic_ai.actions import (
    ActionOptionsEncoder,
    ActionRequest,
    EncodedActionOptions,
    EncodedSelectedAction,
    LegalActionCandidate,
    SelectedActionEncoder,
    action_from_attackers,
    action_from_blockers,
    action_from_choice_accepted,
    action_from_choice_color,
    action_from_choice_ids,
    action_from_choice_index,
    action_from_priority_candidate,
    build_priority_candidates,
    selected_priority_candidate_index,
)
from magic_ai.game_state import (
    GameCardState,
    GameStateEncoder,
    GameStateSnapshot,
    ManaPoolState,
    PendingOptionState,
    PendingState,
    PlayerState,
)
from magic_ai.model import ActionTrace, PolicyStep, PPOPolicy
from magic_ai.ppo import (
    PPOStats,
    RolloutStep,
    merge_pending_into_state,
    ppo_update,
    rollout_step_from_policy,
    terminal_returns,
)

__all__ = [
    "ActionOptionsEncoder",
    "ActionRequest",
    "ActionTrace",
    "EncodedActionOptions",
    "EncodedSelectedAction",
    "GameCardState",
    "GameStateEncoder",
    "GameStateSnapshot",
    "LegalActionCandidate",
    "ManaPoolState",
    "PPOPolicy",
    "PPOStats",
    "PendingOptionState",
    "PendingState",
    "PlayerState",
    "PolicyStep",
    "RolloutStep",
    "SelectedActionEncoder",
    "action_from_attackers",
    "action_from_blockers",
    "action_from_choice_accepted",
    "action_from_choice_color",
    "action_from_choice_ids",
    "action_from_choice_index",
    "action_from_priority_candidate",
    "build_priority_candidates",
    "merge_pending_into_state",
    "ppo_update",
    "rollout_step_from_policy",
    "selected_priority_candidate_index",
    "terminal_returns",
]
