"""Utilities for Magic AI experiments."""

from magic_ai.actions import (
    ActionOptionsEncoder,
    ActionRequest,
    EncodedSelectedAction,
    LegalActionCandidate,
    ParsedActionInputs,
    SelectedActionEncoder,
    action_from_attackers,
    action_from_blockers,
    action_from_choice_accepted,
    action_from_choice_color,
    action_from_choice_ids,
    action_from_choice_index,
    action_from_priority_candidate,
    build_priority_candidates,
    selected_priority_candidate_index,
)
from magic_ai.buffer import NativeTrajectoryBuffer, RolloutBuffer
from magic_ai.game_state import (
    GameCardState,
    GameStateEncoder,
    GameStateSnapshot,
    ManaPoolState,
    ParsedGameState,
    PendingOptionState,
    PendingState,
    PlayerState,
)
from magic_ai.model import (
    ActionTrace,
    ParsedStep,
    PolicyStep,
    PPOPolicy,
)
from magic_ai.native_encoder import NativeBatchEncoder, NativeEncodedBatch, NativeEncodingError
from magic_ai.ppo import (
    PPOStats,
    RolloutStep,
    ppo_update,
    terminal_returns,
)

__all__ = [
    "ActionOptionsEncoder",
    "ActionRequest",
    "ActionTrace",
    "EncodedSelectedAction",
    "GameCardState",
    "GameStateEncoder",
    "GameStateSnapshot",
    "LegalActionCandidate",
    "ManaPoolState",
    "NativeBatchEncoder",
    "NativeEncodedBatch",
    "NativeEncodingError",
    "NativeTrajectoryBuffer",
    "PPOPolicy",
    "PPOStats",
    "ParsedActionInputs",
    "ParsedGameState",
    "ParsedStep",
    "RolloutBuffer",
    "PendingOptionState",
    "PendingState",
    "PlayerState",
    "PolicyStep",
    "RolloutStep",
    "SelectedActionEncoder",
    "action_from_attackers",
    "action_from_blockers",
    "action_from_choice_accepted",
    "action_from_choice_color",
    "action_from_choice_ids",
    "action_from_choice_index",
    "action_from_priority_candidate",
    "build_priority_candidates",
    "ppo_update",
    "selected_priority_candidate_index",
    "terminal_returns",
]
